export const events = [
  {
    slug: 'meet-with-alumni',
    title: 'Meet with Alumni',
    date: '14 August 2021',
    sortDate: '2021-08-14',
    time: '3:00 PM',
    venue: 'Virtual Meetup',
    type: 'Virtual Session',
    coverImage: '/images/events/E1.jpg',
    description: 'The Department of CSE arranged a virtual meetup among final-year students, recent graduates, and alumni.',
    organizer: 'GRACE • Department of CSE',
    gallery: ['/images/events/E1.jpg'],
    details: [
      'Final-year students, recent graduates, and alumni came together in a virtual discussion.',
      'Chief Guest: Prof. Dr. Md. Saiful Azad, Chairman and Professor, Dept. of CSE.',
      'Special Guest: Syed Ahsanul Kabir, Associate Professor, Dept. of CSE.',
    ],
  },
  {
    slug: 'lets-do-devops',
    title: 'Let’s do DevOps – Part 1: A Beginner’s Journey',
    date: '30 October 2021',
    sortDate: '2021-10-30',
    day: 'Saturday',
    time: '08:00 PM',
    venue: 'Online',
    type: 'Workshop',
    coverImage: '/images/events/E2.jpg',
    description: 'A beginner-friendly DevOps session designed to help students begin their journey into modern software practices.',
    organizer: 'GRACE • Community Learning Initiative',
    gallery: ['/images/events/E2.jpg'],
    details: [
      'Instructor: Fakhar Uddin Arnob, Senior Software Engineer & Team Lead, ADN DigiNet Limited.',
      'A practical introduction to DevOps concepts and tools for beginners.',
    ],
  },
  {
    slug: 'cse-iftar-mahfil-2024',
    title: 'CSE IFTAR MAHFIL 2024 & ISLAMIC OLYMPIAD 2.0',
    date: '29 March 2024',
    sortDate: '2024-03-29',
    venue: 'A302 (Seminar Hall) & A409 (Syndicate Room)',
    type: 'Community Event',
    coverImage: '/images/events/E3.jpg',
    description: 'A combined Iftar gathering and Islamic quiz and calligraphy competition organized by GUCC and GAACSE.',
    organizer: 'GRACE • GUCC',
    gallery: ['/images/events/E3.jpg'],
    details: [
      'Islamic Olympiad 2.0 included an Islamic Quiz Competition and Islamic Calligraphy Competition.',
      'In association with IEEE GUB SB, IEEE CS GUB Student Chapter, and BASIS Student’s Forum GUB Chapter.',
    ],
  },
  {
    slug: 'career-compass-v1',
    title: 'Career Compass v1.0',
    date: '1 June 2024',
    sortDate: '2024-06-01',
    venue: 'Green University of Bangladesh',
    type: 'Career Program',
    coverImage: '/images/events/E4.jpg',
    description: 'GRACE’s first Career Compass session introduced students to the software industry through a 10-session orientation and career-focused learning track.',
    organizer: 'GRACE',
    gallery: ['/images/events/E4.jpg'],
    details: [
      'Orientation Class: 1st June 2024',
      'Total Sessions: 10',
      'Open to: All Departments',
      'Registration Fee: 150 BDT',
      'Prizes: Quiz winners received a 100% discount on the next event.',
      'Certification: Provided upon completion.',
      'Lecture topics included job hunting, problem solving, Git & GitHub, OOP, DSA, system design, and microservices.',
      'Esteemed guests: Prof. Dr. Md. Saiful Azad, Prof. Dr. Md. Ahsan Habib, and Dr. Muhammad Abul Hasan.',
      'Featured alumni speaker: Rijwan Hossain, Sr. Software Engineer & Instructor.',
    ],
  },
  {
    slug: 'master-odoo-technical-development',
    title: 'Master Odoo Technical Development',
    date: '2024',
    sortDate: '2024-01-01',
    venue: 'Online',
    type: 'Course',
    coverImage: '/images/events/E5_1.jpg',
    description: 'A 4–5 month online training program focused on Odoo technical development and career readiness.',
    organizer: 'GRACE',
    gallery: ['/images/events/E5_1.jpg', '/images/events/E5_2.jpg'],
    details: [
      'Course Duration: 4–5 months (16–20 weeks)',
      'Schedule: 1 class/week, 2 hours/session',
      'Mode: Online',
      'Instructor: Kaushik Ahmed Apu, Sr. Odoo Expert (HubXpert), Co-Founder of FoneBox Inc., and ex-Sr. Software Engineer at Kolpolok Limited.',
      'Includes: certificate of completion, hands-on projects, and merit-based internship, part-time, or full-time job opportunities.',
    ],
  },
  {
    slug: 'grace-reboot-day-logo-reveal',
    title: 'GRACE Reboot Day & Logo Reveal',
    date: '09 August 2025',
    sortDate: '2025-08-09',
    time: '11:00 AM – 01:00 PM',
    venue: 'A-302 (Seminar Hall)',
    type: 'Launch Event',
    coverImage: '/images/events/E6_1.jpg',
    description: 'A special GRACE day combining achievement recognition, alumni connection, and the launch of the new GRACE identity and Java Spring Mastery course.',
    organizer: 'GRACE',
    gallery: ['/images/events/E6_1.jpg', '/images/events/E6_2.jpg'],
    details: [
      'Highlights included prize and certificate giving, GRACE logo reveal, seminar and course launch, alumni meetup, and more.',
      'Chief Guest: Prof. Dr. Md. Saiful Azad, Dean, FSE, GUB.',
      'Special Guest: Syed Ahsanul Kabir, Associate Professor, Dept. of CSE, GUB.',
      'Session Chair: Prof. Dr. Md. Ahsan Habib, Chairperson & Professor, Dept. of CSE, GUB.',
      'GRACE leadership included K M Ajharul Abedeen, Riyan Sajib Miha, Md. Zahidul Hasan, and Md. Jahid Hassan.',
      'Instructors: Abu Salek Shaon and Saifur Rahman Sabir.',
    ],
  },
  {
    slug: 'java-spring-mastery',
    title: 'Java with Spring Mastery: From Zero to Live Project',
    date: '2025',
    sortDate: '2025-01-01',
    venue: 'Live Project Course',
    type: 'Course Launch',
    coverImage: '/images/events/E7_1.jpg',
    description: 'A rigorous hands-on Java Spring course designed to help students build real production-level projects and learn from industry engineers.',
    organizer: 'GRACE',
    gallery: ['/images/events/E7_1.jpg', '/images/events/E7_2.jpg', '/images/events/E7_3.jpg'],
    details: [
      'The course emphasized real-world project work, open-source contribution, and learning directly from industry experts.',
      'Participants received a verifiable certificate after completion and access to project-based learning opportunities.',
      'Instructors: Abu Salek Shaon, Principal Software Engineer, LEADS Corporation Ltd.; Saifur Rahman Sabir, Software Engineer, Unisoft Systems Ltd.',
    ],
  },
];

export const sortedEvents = [...events].sort((a, b) => new Date(b.sortDate) - new Date(a.sortDate));
